"""Export the current FastAPI OpenAPI schema as Markdown."""
from __future__ import annotations

import json
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))


OUTPUT_PATH = BACKEND_DIR.parent / "docs" / "API.md"


def main() -> None:
    """Write the application schema in a Markdown JSON fence."""
    from server import app

    schema = json.dumps(app.openapi(), indent=2)
    OUTPUT_PATH.write_text(
        "# PHI Handling Console API\n\n"
        "Generated by `backend/scripts/export_openapi.py`. Regenerate after any route change; "
        "do not hand-edit this file.\n\n"
        f"```json\n{schema}\n```\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
