"""Synthetic study-form PDF generator (Phase C1 corpus forms component).

Two output modes:

* **Digital PDF** — text is written as a normal PDF text layer via
  ``fpdf2``. The ``pypdf.extract_text`` fast path picks it up directly;
  no OCR needed.
* **Image-only PDF** — the same content is first rendered to a PIL image
  (rasterised header + body) then wrapped as a JPEG-only PDF via Pillow.
  ``pypdf.extract_text`` returns almost nothing on this file so the
  intake's OCR fallback (``pytesseract`` + ``pdf2image``) has to fire.

Every planted PHI value returned is a ``PlantedCell``-shaped record the
planter merges into the corpus ground truth so the verifier can score
whether the pipeline caught each form-PHI plant.
"""
from __future__ import annotations

import io
import random
from typing import Any


# The set of PHI value slots we drop into a synthetic study form. Each
# tuple: (label_on_form, generator_fn_key, hipaa_category, expected_action).
# The label is what appears next to the value on the form; the value is
# generated by the same generators the corpus already uses for CSV cells.
_FORM_SLOTS: list[tuple[str, str, str, str]] = [
    ("Patient Full Name", "name",   "A", "scrub_text"),
    ("Date of Birth",     "dob",    "C", "scrub_text"),
    ("Phone",             "phone",  "D", "scrub_text"),
    ("Email",             "email",  "F", "scrub_text"),
    ("Home ZIP",          "zip",    "B", "scrub_text"),
    ("Study Site Contact","phone",  "D", "scrub_text"),
]


def _generator_by_key(key: str):
    from . import scenarios as _S
    return {
        "name":  _S.gen_name,
        "dob":   _S.gen_dob,
        "phone": _S.gen_phone_us,
        "email": _S.gen_email,
        "zip":   _S.gen_zip5,
    }[key]


def _build_form_content(
    scenario_label: str,
    rng: random.Random,
) -> tuple[list[str], list[dict[str, Any]]]:
    """Return ``(lines, planted_values)`` for a single synthetic form.

    ``planted_values`` is a list of ``{label, value, hipaa_category,
    expected_action}`` records; the planter converts these into corpus
    ground-truth cells attached to the form file.
    """
    lines: list[str] = [
        f"Study Protocol - {scenario_label}",
        "Baseline enrollment form (SYNTHETIC — planted PHI, not real).",
        "",
    ]
    planted: list[dict[str, Any]] = []
    for label, key, cat, action in _FORM_SLOTS:
        value = _generator_by_key(key)(rng)
        lines.append(f"{label}: {value}")
        planted.append({
            "label": label, "value": value,
            "hipaa_category": cat, "expected_action": action,
        })
    lines.extend([
        "",
        "Clinical Notes:",
        (
            f"Patient {planted[0]['value']} reports mild fatigue since "
            "baseline visit. No new symptoms since last month; continue "
            "current medication regimen. Reviewed labs; HbA1c stable."
        ),
    ])
    return lines, planted


def build_digital_pdf(scenario_label: str, rng: random.Random
                     ) -> tuple[bytes, list[dict[str, Any]]]:
    """Emit a digital-text PDF (pypdf.extract_text will pick up the body)."""
    from fpdf import FPDF

    lines, planted = _build_form_content(scenario_label, rng)
    pdf = FPDF(orientation="P", unit="mm", format="Letter")
    pdf.set_left_margin(15)
    pdf.set_right_margin(15)
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    epw = pdf.epw  # effective page width honouring the margins
    for line in lines:
        # fpdf2 core Helvetica font only supports latin-1; replace
        # unrenderable diacritics with a safe fallback so a name from
        # the generator does not crash the emit.
        safe = line.encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(w=epw, h=7, text=safe)
    out = pdf.output()   # fpdf2 >=2.7 returns bytearray by default
    return bytes(out), planted


def build_scanned_pdf(scenario_label: str, rng: random.Random
                     ) -> tuple[bytes, list[dict[str, Any]]]:
    """Emit an image-only PDF — no text layer.

    Renders the form to a PIL image at 200 dpi so the OCR path can pick
    it up reliably (tesseract at 200 dpi with a large font is > 95 %
    accurate on synthetic content).
    """
    from PIL import Image, ImageDraw, ImageFont

    lines, planted = _build_form_content(scenario_label, rng)
    W, H = 1700, 2200   # ~ US-Letter at 200 dpi
    img = Image.new("RGB", (W, H), color=(255, 255, 255))
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 42
        )
    except Exception:
        font = ImageFont.load_default()
    y = 80
    for line in lines:
        d.text((80, y), line, fill=(0, 0, 0), font=font)
        y += 66

    buf = io.BytesIO()
    img.save(buf, "PDF", resolution=200.0)
    return buf.getvalue(), planted
