"""
Paper-ready camera-ready assets -- reads ONLY artifact JSONs (never hand-typed
numbers) and emits booktabs LaTeX + Markdown tables for the manuscript.

CLI:
    python -m harness.make_paper_assets --results-dir benchmarks/results \\
        --out-dir docs/paper_assets

Emits:
    (a) table_benchmark.tex + .md -- Phase-4 comparison (benchmarks/collect_results.py
        output re-rendered as booktabs LaTeX), one tabular per jurisdiction
        (rows=tools; cols=strict P/R/F1, macro-F1, gap rate; not_run rows kept
        with a reason footnote).
    (b) table_system.tex + .md -- Phase-3 system results for IN/US/held-out
        (redaction recall, leaks, residual findings, quarantine/blank/cap
        counts, human_review_rate, header_classification_agreement,
        classifier_path).
    (c) table_corpus.tex + .md -- dataset statistics from corpus/MANIFEST.json
        (per jurisdiction: files, records, spans).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from benchmarks.collect_results import JURISDICTIONS, collect

SYSTEM_RUNS: List[tuple[str, str]] = [
    ("India (seed 42)", "phi-system-in"),
    ("USA (seed 42)", "phi-system-us"),
    ("India held-out (seed 1337)", "phi-system-in-heldout"),
]


def _tex_escape(s: str) -> str:
    return (
        str(s)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None:
        return "--"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


# ---------------------------------------------------------------------------
# (a) Benchmark comparison table
# ---------------------------------------------------------------------------


def build_table_benchmark(results_dir: Path) -> tuple[str, str]:
    by_jurisdiction = collect(results_dir)

    md_lines: List[str] = ["# Table: Detection Benchmark Comparison", ""]
    tex_lines: List[str] = [
        "% Auto-generated by harness/make_paper_assets.py -- DO NOT EDIT BY HAND.",
        "% Source: benchmarks/results/*/*_benchmark_result.json via benchmarks/collect_results.py",
        "",
    ]

    for jur in JURISDICTIONS:
        rows = by_jurisdiction[jur]
        md_lines.append(f"## Jurisdiction: {jur}")
        md_lines.append("")
        md_lines.append("| Tool | Strict P | Strict R | Strict F1 | Macro-F1 | Gap rate |")
        md_lines.append("|---|---|---|---|---|---|")

        tex_lines.append(f"\\begin{{table}}[htbp]")
        tex_lines.append(f"\\centering")
        tex_lines.append(f"\\caption{{Detection benchmark, jurisdiction: {jur}}}")
        tex_lines.append(f"\\label{{tab:benchmark-{jur}}}")
        tex_lines.append(r"\begin{tabular}{lrrrrr}")
        tex_lines.append(r"\toprule")
        tex_lines.append(r"Tool & Strict P & Strict R & Strict F1 & Macro-F1 & Gap rate \\")
        tex_lines.append(r"\midrule")

        for row in rows:
            if row["status"] == "not_run":
                md_lines.append(f"| {row['tool']} | not\\_run | | | | (see footnote) |")
                tex_lines.append(
                    f"{_tex_escape(row['tool'])} & \\multicolumn{{5}}{{l}}{{not run$^\\dagger$}} \\\\"
                )
                continue
            md_lines.append(
                f"| {row['tool']} | {_fmt(row['strict_precision'])} | {_fmt(row['strict_recall'])} | "
                f"{_fmt(row['strict_f1'])} | {_fmt(row['macro_f1'])} | {_fmt(row['gap_detection_rate'])} |"
            )
            tex_lines.append(
                f"{_tex_escape(row['tool'])} & {_fmt(row['strict_precision'])} & "
                f"{_fmt(row['strict_recall'])} & {_fmt(row['strict_f1'])} & "
                f"{_fmt(row['macro_f1'])} & {_fmt(row['gap_detection_rate'])} \\\\"
            )
        md_lines.append("")

        tex_lines.append(r"\bottomrule")
        tex_lines.append(r"\end{tabular}")
        tex_lines.append(
            r"\par\footnotesize$\dagger$ not\_run reasons: see docs/SOTA\_COMPARISON.md "
            r"and benchmarks/results/comparison\_table.md (full reason text, package/env-gate specific)."
        )
        tex_lines.append(r"\end{table}")
        tex_lines.append("")

    return "\n".join(md_lines), "\n".join(tex_lines)


# ---------------------------------------------------------------------------
# (b) System (Phase 3) results table
# ---------------------------------------------------------------------------


def build_table_system(results_dir: Path) -> tuple[str, str]:
    md_lines: List[str] = ["# Table: System Run Results (phi_engine scrub, Phase 3)", ""]
    md_lines.append(
        "| Run | Redaction recall | Leaks | Residual findings | Quarantined | Blanked | "
        "Age-capped | Human review rate | Header agreement | Classifier path |"
    )
    md_lines.append("|---|---|---|---|---|---|---|---|---|---|")

    tex_lines: List[str] = [
        "% Auto-generated by harness/make_paper_assets.py -- DO NOT EDIT BY HAND.",
        "% Source: benchmarks/results/phi-system-*/phi_system_result.json",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{phi\_engine scrub system results (Phase 3)}",
        r"\label{tab:system-results}",
        r"\begin{tabular}{lrrrrrrrrl}",
        r"\toprule",
        r"Run & Recall & Leaks & Residual & Quar. & Blank & Cap & HRR & Agreement & Classifier \\",
        r"\midrule",
    ]

    for label, dirname in SYSTEM_RUNS:
        path = results_dir / dirname / "phi_system_result.json"
        if not path.is_file():
            md_lines.append(f"| {label} | MISSING ({path}) | | | | | | | | |")
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        redaction = data["redaction"]
        fail_closed = data["fail_closed"]
        residual = data["residual"]
        ai_layer = data["ai_layer"]

        n_leaks = sum(l["count"] for l in redaction["leaks"])
        n_residual = (residual.get("presidio_finding_count") or 0) + (
            residual.get("legacy_finding_count") or 0
        )

        md_lines.append(
            "| {label} | {recall} | {leaks} | {residual} | {quar} | {blank} | {cap} | "
            "{hrr} | {agree} | {clf} |".format(
                label=label,
                recall=_fmt(redaction["redaction_recall"]),
                leaks=n_leaks,
                residual=n_residual,
                quar=f"{fail_closed['quarantined_rows_observed']}/{fail_closed['planted_orphan_rows']}",
                blank=f"{fail_closed['blanked_dates_observed']}/{fail_closed['planted_unparseable_dates']}",
                cap=f"{fail_closed['age_cap_90plus_observed']}/{fail_closed['planted_age_cap_subjects']}",
                hrr=_fmt(ai_layer["human_review_rate"]),
                agree=_fmt(ai_layer["header_classification_agreement"]),
                clf=ai_layer["classifier_path"],
            )
        )
        tex_lines.append(
            "{label} & {recall} & {leaks} & {residual} & {quar} & {blank} & {cap} & "
            "{hrr} & {agree} & {clf} \\\\".format(
                label=_tex_escape(label),
                recall=_fmt(redaction["redaction_recall"]),
                leaks=n_leaks,
                residual=n_residual,
                quar=f"{fail_closed['quarantined_rows_observed']}/{fail_closed['planted_orphan_rows']}",
                blank=f"{fail_closed['blanked_dates_observed']}/{fail_closed['planted_unparseable_dates']}",
                cap=f"{fail_closed['age_cap_90plus_observed']}/{fail_closed['planted_age_cap_subjects']}",
                hrr=_fmt(ai_layer["human_review_rate"]),
                agree=_fmt(ai_layer["header_classification_agreement"]),
                clf=_tex_escape(ai_layer["classifier_path"]),
            )
        )

    tex_lines.append(r"\bottomrule")
    tex_lines.append(r"\end{tabular}")
    tex_lines.append(
        r"\par\footnotesize Quar./Blank/Cap columns show observed/planted counts "
        r"(fail-closed edge-case verification, Step 2.3). HRR = human\_review\_rate. "
        r"Agreement = binary PHI-vs-non-PHI classifier agreement (see "
        r"phi\_system\_result.json ai\_layer.header\_classification\_agreement\_definition)."
    )
    tex_lines.append(r"\end{table}")

    return "\n".join(md_lines), "\n".join(tex_lines)


# ---------------------------------------------------------------------------
# (c) Corpus statistics table
# ---------------------------------------------------------------------------


def build_table_corpus(project_root: Path) -> tuple[str, str]:
    manifest_path = project_root / "corpus" / "MANIFEST.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    file_counts: Dict[str, int] = {}
    for key in manifest["files"]:
        jur = key.split("/", 1)[0]
        file_counts[jur] = file_counts.get(jur, 0) + 1

    md_lines: List[str] = [
        "# Table: PHI-Bench Corpus Statistics",
        "",
        f"Seed: {manifest['seed']}. Manifest sha256 (recorded in release_evidence.json).",
        "",
        "| Jurisdiction | Files | Records | Spans |",
        "|---|---|---|---|",
    ]
    tex_lines: List[str] = [
        "% Auto-generated by harness/make_paper_assets.py -- DO NOT EDIT BY HAND.",
        "% Source: corpus/MANIFEST.json",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{PHI-Bench corpus statistics (seed " + str(manifest["seed"]) + ")}",
        r"\label{tab:corpus-stats}",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Jurisdiction & Files & Records & Spans \\",
        r"\midrule",
    ]

    total_records = 0
    total_spans = 0
    for jur in sorted(manifest["totals"].keys()):
        t = manifest["totals"][jur]
        files = file_counts.get(jur, 0)
        md_lines.append(f"| {jur} | {files} | {t['records']} | {t['spans']} |")
        tex_lines.append(f"{_tex_escape(jur)} & {files} & {t['records']} & {t['spans']} \\\\")
        total_records += t["records"]
        total_spans += t["spans"]

    md_lines.append(f"| **Total** | {sum(file_counts.values())} | {total_records} | {total_spans} |")
    tex_lines.append(r"\midrule")
    tex_lines.append(
        f"\\textbf{{Total}} & {sum(file_counts.values())} & {total_records} & {total_spans} \\\\"
    )
    tex_lines.append(r"\bottomrule")
    tex_lines.append(r"\end{tabular}")
    tex_lines.append(r"\end{table}")

    return "\n".join(md_lines), "\n".join(tex_lines)


def main(argv: List[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, default=_PROJECT_ROOT / "benchmarks" / "results")
    parser.add_argument("--out-dir", type=Path, default=_PROJECT_ROOT / "docs" / "paper_assets")
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    bench_md, bench_tex = build_table_benchmark(args.results_dir)
    (args.out_dir / "table_benchmark.md").write_text(bench_md, encoding="utf-8")
    (args.out_dir / "table_benchmark.tex").write_text(bench_tex, encoding="utf-8")

    sys_md, sys_tex = build_table_system(args.results_dir)
    (args.out_dir / "table_system.md").write_text(sys_md, encoding="utf-8")
    (args.out_dir / "table_system.tex").write_text(sys_tex, encoding="utf-8")

    corpus_md, corpus_tex = build_table_corpus(_PROJECT_ROOT)
    (args.out_dir / "table_corpus.md").write_text(corpus_md, encoding="utf-8")
    (args.out_dir / "table_corpus.tex").write_text(corpus_tex, encoding="utf-8")

    print(f"Wrote table_benchmark.{{md,tex}}, table_system.{{md,tex}}, table_corpus.{{md,tex}} to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
